[package]
name = "descriptor"
version = "0.1.0-pre"
authors = ["Sam Phippen <samphippen@googlemail.com>"]

[dependencies]
lazy_static = "0.1.15"

[dev-dependencies]
expector = { path = "../expector" }
